management:
  health:
    show-details: "always"
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,shutdown,prometheus"
      path-mapping:
        health: "health"
        shutdown: "shutdown"
        prometheus: "metrics"

config:
  adminUser: ${ADMIN_USER:myscoutee@gmail.com}
  firebase-service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:./secrets/firebase-service-account.json}

fcm:
  url: "https://fcm.googleapis.com/fcm/send"
  apiKey: ${FCM_API_KEY:}

spring:
  config:
    import: optional:file:./secrets/application-dev-secrets.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      #authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
      username: ${MONGODB_USERNAME:guest}
      password: ${MONGODB_PASSWORD:guest}
      database: ${MONGODB_DATABASE:myscoutee_db}
  mqtt:
    client-id: spring
    url: tcp://mqtt:1883
    username: spring
    password: pwd
    default-topic: channels/pages/#
    timeout: 20000
    server-ip: 172.18.0.2

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
